stages:
  - stage: ubuntu_latest
    displayName: 'ubuntu-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: Compile
        displayName: '⚙️ Compile'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Restore Compile --skip'
      - job: Test
        displayName: '🚦 Test 🧩'
        dependsOn: [ Compile ]
        strategy:
          parallel: 2
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Test --skip --test-partition $(System.JobPositionInPhase)'
      - job: Pack
        displayName: '📦 Pack'
        dependsOn: [ Compile ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Pack --skip'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: output
              pathtoPublish: 'output'
  - stage: windows_latest
    displayName: 'windows-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'windows-latest'
    jobs:
      - job: Compile
        displayName: '⚙️ Compile'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Restore Compile --skip'
      - job: Test
        displayName: '🚦 Test 🧩'
        dependsOn: [ Compile ]
        strategy:
          parallel: 2
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Test --skip --test-partition $(System.JobPositionInPhase)'
      - job: Pack
        displayName: '📦 Pack'
        dependsOn: [ Compile ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Pack --skip'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: output
              pathtoPublish: 'output'
  - stage: macOS_latest
    displayName: 'macOS-latest'
    dependsOn: [  ]
    pool:
      vmImage: 'macOS-latest'
    jobs:
      - job: Compile
        displayName: '⚙️ Compile'
        dependsOn: [  ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Restore Compile --skip'
      - job: Test
        displayName: '🚦 Test 🧩'
        dependsOn: [ Compile ]
        strategy:
          parallel: 2
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Test --skip --test-partition $(System.JobPositionInPhase)'
      - job: Pack
        displayName: '📦 Pack'
        dependsOn: [ Compile ]
        steps:
          - task: PowerShell@2
            inputs:
              filePath: 'build.ps1'
              arguments: 'Pack --skip'
          - task: PublishBuildArtifacts@1
            inputs:
              artifactName: output
              pathtoPublish: 'output'
